feat: total overhaul of pipeline to support silver,gold,golddr.

diff --git a/.github/workflows/.deployer.yml b/.github/workflows/.deployer.yml
--- a/.github/workflows/.deployer.yml
+++ b/.github/workflows/.deployer.yml
@@ -9,9 +9,9 @@ on:
       ### Typical / recommended
       atomic:
         description: Atomic deployment?  That means fail all or nothing
-        default: true
+        default: false
         required: false
-        type: string
+        type: boolean
       directory:
         description: Chart directory
         default:  'charts/app'
@@ -22,13 +22,12 @@ on:
         required: false
         type: string
       oc_server:
-        default: https://api.gold.devops.gov.bc.ca:6443
-        description: 'OpenShift server'
+        default: https://api.silver.devops.gov.bc.ca:6443
+        description: OpenShift server
         required: false
         type: string
       params:
-        description: 'Extra parameters to pass to helm upgrade'
-        default: ''
+        description: Extra parameters to pass to helm upgrade
         required: false
         type: string
       tag:
@@ -36,11 +35,21 @@ on:
         required: false
         type: string
       triggers:
-        description: Paths used to trigger a deployment; e.g. (./frontend/)
+        description: Paths used to trigger a deployment; e.g. ('./backend/' './frontend/)
         required: false
         type: string
       db_user:
         description: The database user
+        required: false
+        default: 'app'
+        type: string
+      debug:
+        description: Debug mode
+        default: false
+        required: false
+        type: boolean
+      db_triggers:
+        description: Paths used to trigger a database deployment; e.g. ('charts/crunchy/')
         required: false
         type: string
 
@@ -57,9 +66,12 @@ on:
         type: string
 
     outputs:
+      tag:
+        description: 'Which tag was used for deployment?'
+        value: ${{ jobs.deploy.outputs.tag }}
       triggered:
         description: 'Has a deployment has been triggered?'
-        value: ${{ jobs.deployer.outputs.triggered }}
+        value: ${{ jobs.deploy.outputs.triggered }}
 
     secrets:
       oc_namespace:
@@ -68,32 +80,35 @@ on:
       oc_token:
         description: OpenShift token
         required: true
-      oc_server:
-        description: OpenShift server url
-        required: true
+
+permissions: {}
 
 jobs:
-  deployer:
+  deploy:
     name: Stack
     environment: ${{ inputs.environment }}
     runs-on: ubuntu-24.04
     outputs:
-      triggered: ${{ steps.triggers.outputs.triggered }}
+      tag: ${{ inputs.tag || steps.pr.outputs.pr }}
+      triggered: ${{ steps.deploy.outputs.triggered }}
     steps:
-      ### Triggers, tag and release
-
-      # Check triggers (omitted or matched) for deployment
-      - uses: bcgov-nr/action-diff-triggers@v0.2.0
-        id: triggers
+      - uses: bcgov/action-crunchy@v1.2.5
+        name: Deploy Crunchy
+        id: deploy_crunchy
         with:
-          triggers: ${{ inputs.triggers }}
+          oc_namespace: ${{ secrets.OC_NAMESPACE }}
+          oc_token: ${{ secrets.OC_TOKEN }}
+          environment: ${{ inputs.environment }}
+          values_file: charts/crunchy/values.yml
+          triggers: ${{ inputs.db_triggers }}
+
 
       # Variables
-      - if: ${{ steps.triggers.outputs.triggered == 'true' && inputs.tag  == '' }}
+      - if: inputs.tag  == ''
         id: pr
-        uses: bcgov-nr/action-get-pr@v0.0.1
-      - if: steps.triggers.outputs.triggered == 'true'
-        id: vars
+        uses: bcgov/action-get-pr@21f9351425cd55a98e869ee28919a512aa30647d # v0.0.1
+
+      - id: vars
         run: |
           # Vars: tag and release
 
@@ -116,82 +131,61 @@ jobs:
           echo "release=${release}" >> $GITHUB_OUTPUT
           echo "version=${version}" >> $GITHUB_OUTPUT
 
-      ### Deploy
-      - name: Install CLI tools from OpenShift Mirror
-        if: steps.triggers.outputs.triggered == 'true'
-        uses: redhat-actions/openshift-tools-installer@v1
+      - name: Stop pre-existing deployments on PRs (status = pending-upgrade)
+        if: github.event_name == 'pull_request'
+        uses: bcgov/action-oc-runner@10033668ef4374d9bb78149faa73e4ccda0e93dd # v1.2.3
         with:
-          oc: "4"
+          oc_namespace: ${{ secrets.oc_namespace }}
+          oc_token: ${{ secrets.oc_token }}
+          oc_server: ${{ vars.oc_server }}
+          triggers: ${{ inputs.triggers }}
+          commands: |
+            # Interrupt any previous deployments (PR only)
+            PREVIOUS=$(helm status ${{ steps.vars.outputs.release }} -o json | jq .info.status || true)
+            if [[ ${PREVIOUS} =~ pending ]]; then
+              echo "Rollback triggered"
+              helm rollback ${{ steps.vars.outputs.release }} || \
+                helm uninstall ${{ steps.vars.outputs.release }}
+            fi
 
-      # OC login and acquire short lived token
-      - if: steps.triggers.outputs.triggered == 'true'
-        shell: bash
-        run: |
-          # OC Login
-          OC_TEMP_TOKEN=$(curl -k -X POST ${{ secrets.oc_server }}/api/v1/namespaces/${{ secrets.oc_namespace }}/serviceaccounts/pipeline/token --header "Authorization: Bearer ${{ secrets.oc_token }}" -d '{"spec": {"expirationSeconds": 600}}' -H 'Content-Type: application/json; charset=utf-8' | jq -r '.status.token' )
+      - uses: actions/checkout@v4
+      - name: Debug Values File
+        if: inputs.debug == 'true'
+        run: ls -l charts/crunchy/values.yml
 
-          oc login --token=$OC_TEMP_TOKEN --server=${{ secrets.oc_server }}
-          oc project ${{ secrets.oc_namespace }} # Safeguard!
+      - name: Helm Deploy
+        id: deploy
+        uses: bcgov/action-oc-runner@10033668ef4374d9bb78149faa73e4ccda0e93dd # v1.2.3
+        with:
+          oc_namespace: ${{ secrets.oc_namespace }}
+          oc_token: ${{ secrets.oc_token }}
+          oc_server: ${{ vars.oc_server }}
+          triggers: ${{ inputs.triggers }}
+          ref: ${{ github.ref }}
+          commands: |
+            # Deploy
 
-      # Only stop pre-existing deployments on PRs (status = pending-upgrade)
-      - if: steps.triggers.outputs.triggered == 'true' && github.event_name == 'pull_request'
-        run: |
-          # Interrupt any previous deployments (PR only)
-          PREVIOUS=$(helm status ${{ steps.vars.outputs.release }} -o json | jq .info.status || true)
-          if [[ ${PREVIOUS} =~ pending ]]; then
-            echo "Rollback triggered"
-            helm rollback ${{ steps.vars.outputs.release }} || \
-              helm uninstall ${{ steps.vars.outputs.release }}
-          fi
+            # If directory provided, cd to it
+            [ -z "${{ inputs.directory }}" ]|| cd ${{ inputs.directory }}
 
-      # Package Helm chart
-      - if: steps.triggers.outputs.triggered == 'true'
-        uses: actions/checkout@v4
-      - if: steps.triggers.outputs.triggered == 'true'
-        working-directory: ${{ inputs.directory }}
-        run: |
-          # Helm package
-          sed -i 's/^name:.*/name: ${{ github.event.repository.name }}/' Chart.yaml
-          helm package -u . --app-version="tag-${{ steps.vars.outputs.tag }}_run-${{ github.run_number }}" --version=${{ steps.pr.outputs.pr || steps.vars.outputs.version }}
+            # Helm package
+            sed -i 's/^name:.*/name: ${{ github.event.repository.name }}/' Chart.yaml
+            helm package -u . --app-version="tag-${{ steps.vars.outputs.tag }}_run-${{ github.run_number }}" --version=${{ steps.pr.outputs.pr || steps.vars.outputs.version }}
+            # print the values.yaml file to see the values being used
+            # Helm upgrade/rollout
+            helm upgrade \
+              --set-string global.repository=${{ github.repository }} \
+              --set-string global.tag="${{ steps.vars.outputs.tag }}" \
+              --set-string global.config.databaseUser="${{ inputs.db_user }}" \
+              --set-string global.databaseAlias="${{ steps.deploy_crunchy.outputs.release }}-crunchy" \
+              ${{ inputs.params }} \
+              --install --wait ${{ inputs.atomic && '--atomic' || '' }} ${{ steps.vars.outputs.release }} \
+              --timeout ${{ inputs.timeout-minutes }}m \
+              --values ${{ inputs.values }} \
+              ./${{ github.event.repository.name }}-${{ steps.pr.outputs.pr || steps.vars.outputs.version }}.tgz
 
-      # Deploy Helm chart as atomic, with timeout
-      - if: steps.triggers.outputs.triggered == 'true' && inputs.atomic != 'false'
-        working-directory: ${{ inputs.directory }}
-        run: |
-          # Helm upgrade/rollout - atomic, timeout
-          helm upgrade \
-            --set-string global.repository=${{ github.repository }} \
-            --set-string global.tag=${{ steps.vars.outputs.tag }} \
-            --set-string global.config.databaseUser=${{ inputs.db_user }} \
-            ${{ inputs.params }} \
-            --install --wait --atomic ${{ steps.vars.outputs.release }} \
-            --timeout ${{ inputs.timeout-minutes }}m \
-            --values ${{ inputs.values }} \
-            ./${{ github.event.repository.name }}-${{ steps.pr.outputs.pr || steps.vars.outputs.version }}.tgz
+            # Helm release history
+            helm history ${{ steps.vars.outputs.release }}
 
-      # Deploy Helm chart without atomic or timeout
-      - if: steps.triggers.outputs.triggered == 'true' && inputs.atomic == 'false'
-        working-directory: ${{ inputs.directory }}
-        run: |
-          # Helm upgrade/rollout - non-atomic, no timeout
-          helm upgrade \
-            --set-string global.repository=${{ github.repository }} \
-            --set-string global.tag=${{ steps.vars.outputs.tag }} \
-            ${{ inputs.params }} \
-            ${{ steps.vars.outputs.release }} \
-            --install --wait --values ${{ inputs.values }} \
-            ./${{ github.event.repository.name }}-${{ steps.pr.outputs.pr || steps.vars.outputs.version }}.tgz
-
-      # Helm release history
-      - if: steps.triggers.outputs.triggered == 'true'
-        run: |
-          # Helm release history
-          helm history ${{ steps.vars.outputs.release }}
-
-      ### Cleanup
-
-      # Completed pod cleanup
-      - if: steps.triggers.outputs.triggered == 'true'
-        run: |
-          # Completed pod cleanup
-          oc delete po --field-selector=status.phase==Succeeded || true
+            # Completed pod cleanup
+            oc delete po --field-selector=status.phase==Succeeded || true
